
services:
  manipulator:
    network_mode: "host"
    image: manipulatorfield
    user: "1000:1000"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - ./notebooks:/notebooks
      - ./scripts:/scripts
      - /dev/dri:/dev/dri
    environment:
      - "DISPLAY=${DISPLAY}"
      - XAUTHORITY
      - NVIDIA_DRIVER_CAPABILITIES=all
    command: jupyter-lab --port 9999 --no-browser --LabApp.token='' --allow-root
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, compute, utility]
